server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: http://localhost:8092
          predicates:
            - Path=/book/**
        - id: rating-service
          uri: http://localhost:8091
          predicates:
            - Path=/rating/**
        - id: client-service
          uri: http://localhost:8093
          predicates:
            - Path=/client/**